project:
  type: website
  output-dir: docs

website:
  title: "Aidan McMillan's Awesome CSCI 0451 Blog"
  favicon: img/fav.png
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AidMMcMillan/AidMMcMillan.github.io

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





